FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./




# Use a cache mount for pip
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.txt




COPY . .

ENV DJANGO_SETTINGS_MODULE=online_shop.settings.prod



EXPOSE 8000
# Run migrations and then start Gunicorn
CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn online_shop.wsgi:application -b 0.0.0.0:8000"]
