# Generated by Django 6.0.2 on 2026-02-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='base_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
