# Generated by Django 6.0.2 on 2026-02-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.IntegerField(unique=True)),
                ('category_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_variant_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('site', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('is_archived', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('shipping_type', models.CharField(max_length=50)),
                ('stock_in_digikala', models.IntegerField()),
                ('stock_in_seller_warehouse', models.IntegerField()),
                ('selling_stock', models.IntegerField()),
                ('buy_box_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_buy_box_winner', models.BooleanField(null=True)),
                ('fulfilment_and_delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('external_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.product')),
                ('linked_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
                ('shipment_status', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('commitment_date', models.DateTimeField()),
                ('external_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.product')),
                ('external_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.variant')),
            ],
        ),
    ]
