# Generated by Django 6.0.2 on 2026-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantchannel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantchannel',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
