# Generated by Django 6.0.2 on 2026-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_variantchannel_price_variantchannel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantchannel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
